version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=myproject.settings
    container_name: django-backend
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./auth-vue:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend
    container_name: vue-frontend
    networks:
      - app-network
    tty: true
    stdin_open: true

networks:
  app-network:
    driver: bridge 